### ISSUE TITLE
Custom Data Plugin

### ISSUE THREAD

**Issue by SocraticPhoenix** [SpongePowered/Cookbook#11]
Now that the Data API is reasonably stable, and the data abstractions from common have made it into the main api, a plugin should be written that shows usage of custom data. I know this kind of example would be very useful to me., and I'm sure many others would benefit as well. I think that, in general, the example should include:
- Single data (both primitive, and string-convertible)
- Multi-Data
- Everything required to make the data "work" and be serialized/peristent

(I would write it myself, but I would need some sort of example plugin to follow before I got the hang of it)

**Comment by Faithcaio** [comment]
@gabizou 0d93861bd5f4ec221a536f5a195e44cee35bc18c
If you'd like to take a look

**Comment by phit** [comment]
was covered by https://github.com/SpongePowered/Cookbook/pull/17
